always

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -9,12 +9,16 @@ jobs:
               run: sleep 20
             - name: step-2
               id: step-2
-              run: exit 0
+              run: exit 1
             - name: Runs on failure
               if: failure() && steps.step-2.conclusion == 'failure'
               run: echo 'step-2 has failed'
             - name: run on success
               if: success()
               run: echo run on success
+            - name: runs always
+            # if: success() || failure()
+              if: always()
+              run: echo run on always
             
                
